Importing the drive into google colab

In [4]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

Printing the dataset

In [5]:
import pandas as pd
df = pd.read_excel('/content/drive/MyDrive/dae_dataset.xlsx',sheet_name = 'Sheet1')
print(df)

  Review_ID  Restaurant_Name  Food_Rating  Service_Rating  Ambience_Rating  \
0      R001     Spice Garden            5             4.0              5.0
1      R002         Food Hub            3             NaN              3.0
2      R003      Tasty Bites            2             2.0              3.0
3      R004       Urban Cafe            4             5.0              NaN
4      R005       Green Leaf            3             3.0              4.0
5      R006    Royal Kitchen            5             5.0              5.0
6      R007      Food Corner            1             2.0              2.0
7      R008  The Grill House            4             4.0              NaN
8      R009     Cafe Delight            2             3.0              3.0
9      R010      Spice Villa            4             NaN              5.0

   Overall_Rating                           Review_Text  Feedback
0               5     Excellent food and great ambience  Positive
1               3    Food was okay but service was slow   Neutral
2               2                                   NaN  Negative
3               4          Good food and friendly staff  Positive
4               3       Nice place but food was average       NaN
5               5    Amazing food and excellent service  Positive
6               1                  Very poor experience       NaN
7               4  Delicious food and reasonable prices  Positive
8               2        Food quality needs improvement  Negative
9               4         Great ambience and tasty food  Positive

Printing the first 5 rows

In [6]:
import pandas as pd
df = pd.read_excel('/content/drive/MyDrive/dae_dataset.xlsx',sheet_name = 'Sheet1')
df.head()

,Review_ID,Restaurant_Name,Food_Rating,Service_Rating,Ambience_Rating,Overall_Rating,Review_Text,Feedback
0,R001,Spice Garden,5,4.0,5.0,5,Excellent food and great ambience,Positive
1,R002,Food Hub,3,NaN,3.0,3,Food was okay but service was slow,Neutral
2,R003,Tasty Bites,2,2.0,3.0,2,NaN,Negative
3,R004,Urban Cafe,4,5.0,NaN,4,Good food and friendly staff,Positive
4,R005,Green Leaf,3,3.0,4.0,3,Nice place but food was average,NaN

Printing the last 5 rows

In [7]:
import pandas as pd
df = pd.read_excel('/content/drive/MyDrive/dae_dataset.xlsx',sheet_name = 'Sheet1')
df.tail()

,Review_ID,Restaurant_Name,Food_Rating,Service_Rating,Ambience_Rating,Overall_Rating,Review_Text,Feedback
5,R006,Royal Kitchen,5,5.0,5.0,5,Amazing food and excellent service,Positive
6,R007,Food Corner,1,2.0,2.0,1,Very poor experience,NaN
7,R008,The Grill House,4,4.0,NaN,4,Delicious food and reasonable prices,Positive
8,R009,Cafe Delight,2,3.0,3.0,2,Food quality needs improvement,Negative
9,R010,Spice Villa,4,NaN,5.0,4,Great ambience and tasty food,Positive

Printing the number of reviews(rows) and attributes(columns)

In [8]:
import pandas as pd
df = pd.read_excel('/content/drive/MyDrive/dae_dataset.xlsx',sheet_name = 'Sheet1')
print("Shape:",df.shape)

Shape: (10, 8)

In [9]:
import pandas as pd
df = pd.read_excel('/content/drive/MyDrive/dae_dataset.xlsx',sheet_name = 'Sheet1')
print(df.isnull().sum())

Review_ID          0
Restaurant_Name    0
Food_Rating        0
Service_Rating     2
Ambience_Rating    2
Overall_Rating     0
Review_Text        1
Feedback           2
dtype: int64

Setting Conditions: Printing the reviews whose overall rating is greater than 3

In [10]:
import pandas as pd
df = pd.read_excel('/content/drive/MyDrive/dae_dataset.xlsx',sheet_name = 'Sheet1')
high_review = df[df['Overall_Rating']>=4]
print(high_review)

  Review_ID  Restaurant_Name  Food_Rating  Service_Rating  Ambience_Rating  \
0      R001     Spice Garden            5             4.0              5.0
3      R004       Urban Cafe            4             5.0              NaN
5      R006    Royal Kitchen            5             5.0              5.0
7      R008  The Grill House            4             4.0              NaN
9      R010      Spice Villa            4             NaN              5.0

   Overall_Rating                           Review_Text  Feedback
0               5     Excellent food and great ambience  Positive
3               4          Good food and friendly staff  Positive
5               5    Amazing food and excellent service  Positive
7               4  Delicious food and reasonable prices  Positive
9               4         Great ambience and tasty food  Positive

Printing the attributes of the dataset

In [11]:
import pandas as pd
df = pd.read_excel('/content/drive/MyDrive/dae_dataset.xlsx',sheet_name = 'Sheet1')
df.columns

Index(['Review_ID', 'Restaurant_Name', 'Food_Rating', 'Service_Rating',
       'Ambience_Rating', 'Overall_Rating', 'Review_Text', 'Feedback'],
      dtype='object')

Filling the NaN values with specific value

In [12]:
import pandas as pd
df = pd.read_excel('/content/drive/MyDrive/dae_dataset.xlsx',sheet_name = 'Sheet1')
df["Ambience_Rating"] = df["Ambience_Rating"].fillna("Not rated")
df["Service_Rating"] = df["Service_Rating"].fillna("Not rated")
df["Review_Text"] = df["Review_Text"].fillna("Not reviewed")
df["Feedback"] = df["Feedback"].fillna("No feedback")
print("Dataset after  filling missing values")
print(df)

Dataset after  filling missing values
  Review_ID  Restaurant_Name  Food_Rating Service_Rating Ambience_Rating  \
0      R001     Spice Garden            5            4.0             5.0
1      R002         Food Hub            3      Not rated             3.0
2      R003      Tasty Bites            2            2.0             3.0
3      R004       Urban Cafe            4            5.0       Not rated
4      R005       Green Leaf            3            3.0             4.0
5      R006    Royal Kitchen            5            5.0             5.0
6      R007      Food Corner            1            2.0             2.0
7      R008  The Grill House            4            4.0       Not rated
8      R009     Cafe Delight            2            3.0             3.0
9      R010      Spice Villa            4      Not rated             5.0

   Overall_Rating                           Review_Text     Feedback
0               5     Excellent food and great ambience     Positive
1               3    Food was okay but service was slow      Neutral
2               2                          Not reviewed     Negative
3               4          Good food and friendly staff     Positive
4               3       Nice place but food was average  No feedback
5               5    Amazing food and excellent service     Positive
6               1                  Very poor experience  No feedback
7               4  Delicious food and reasonable prices     Positive
8               2        Food quality needs improvement     Negative
9               4         Great ambience and tasty food     Positive

Printing the reviews in ascending order of rating

In [13]:
import pandas as pd
df = pd.read_excel('/content/drive/MyDrive/dae_dataset.xlsx',sheet_name = 'Sheet1')
print("Restaurants sorted by ratings(Ascending)")
print(df.sort_values(by = "Overall_Rating"))

Restaurants sorted by ratings(Ascending)
  Review_ID  Restaurant_Name  Food_Rating  Service_Rating  Ambience_Rating  \
6      R007      Food Corner            1             2.0              2.0
2      R003      Tasty Bites            2             2.0              3.0
8      R009     Cafe Delight            2             3.0              3.0
4      R005       Green Leaf            3             3.0              4.0
1      R002         Food Hub            3             NaN              3.0
7      R008  The Grill House            4             4.0              NaN
9      R010      Spice Villa            4             NaN              5.0
3      R004       Urban Cafe            4             5.0              NaN
5      R006    Royal Kitchen            5             5.0              5.0
0      R001     Spice Garden            5             4.0              5.0

   Overall_Rating                           Review_Text  Feedback
6               1                  Very poor experience       NaN
2               2                                   NaN  Negative
8               2        Food quality needs improvement  Negative
4               3       Nice place but food was average       NaN
1               3    Food was okay but service was slow   Neutral
7               4  Delicious food and reasonable prices  Positive
9               4         Great ambience and tasty food  Positive
3               4          Good food and friendly staff  Positive
5               5    Amazing food and excellent service  Positive
0               5     Excellent food and great ambience  Positive

Printing the reviews in descending order of rating

In [14]:
import pandas as pd
df = pd.read_excel('/content/drive/MyDrive/dae_dataset.xlsx',sheet_name = 'Sheet1')
print("Restaurants sorted by ratings(Descending)")
print(df.sort_values(by = "Overall_Rating",ascending = False))

Restaurants sorted by ratings(Descending)
  Review_ID  Restaurant_Name  Food_Rating  Service_Rating  Ambience_Rating  \
0      R001     Spice Garden            5             4.0              5.0
5      R006    Royal Kitchen            5             5.0              5.0
9      R010      Spice Villa            4             NaN              5.0
3      R004       Urban Cafe            4             5.0              NaN
7      R008  The Grill House            4             4.0              NaN
1      R002         Food Hub            3             NaN              3.0
4      R005       Green Leaf            3             3.0              4.0
2      R003      Tasty Bites            2             2.0              3.0
8      R009     Cafe Delight            2             3.0              3.0
6      R007      Food Corner            1             2.0              2.0

   Overall_Rating                           Review_Text  Feedback
0               5     Excellent food and great ambience  Positive
5               5    Amazing food and excellent service  Positive
9               4         Great ambience and tasty food  Positive
3               4          Good food and friendly staff  Positive
7               4  Delicious food and reasonable prices  Positive
1               3    Food was okay but service was slow   Neutral
4               3       Nice place but food was average       NaN
2               2                                   NaN  Negative
8               2        Food quality needs improvement  Negative
6               1                  Very poor experience       NaN

Adding a new column(Category)

In [15]:
import pandas as pd
df = pd.read_excel('/content/drive/MyDrive/dae_dataset.xlsx',sheet_name = 'Sheet1')
print("Printing After adding a new column")
df['Category'] = df['Overall_Rating'].apply(
      lambda x:'Most Popular' if x==5
      else 'Popular' if x==4
      else 'Not Popular')
print(df)

Printing After adding a new column
  Review_ID  Restaurant_Name  Food_Rating  Service_Rating  Ambience_Rating  \
0      R001     Spice Garden            5             4.0              5.0
1      R002         Food Hub            3             NaN              3.0
2      R003      Tasty Bites            2             2.0              3.0
3      R004       Urban Cafe            4             5.0              NaN
4      R005       Green Leaf            3             3.0              4.0
5      R006    Royal Kitchen            5             5.0              5.0
6      R007      Food Corner            1             2.0              2.0
7      R008  The Grill House            4             4.0              NaN
8      R009     Cafe Delight            2             3.0              3.0
9      R010      Spice Villa            4             NaN              5.0

   Overall_Rating                           Review_Text  Feedback  \
0               5     Excellent food and great ambience  Positive
1               3    Food was okay but service was slow   Neutral
2               2                                   NaN  Negative
3               4          Good food and friendly staff  Positive
4               3       Nice place but food was average       NaN
5               5    Amazing food and excellent service  Positive
6               1                  Very poor experience       NaN
7               4  Delicious food and reasonable prices  Positive
8               2        Food quality needs improvement  Negative
9               4         Great ambience and tasty food  Positive

       Category
0  Most Popular
1   Not Popular
2   Not Popular
3       Popular
4   Not Popular
5  Most Popular
6   Not Popular
7       Popular
8   Not Popular
9       Popular

Performing the operations on the dataset using aggregate functions

In [16]:
import pandas as pd
df = pd.read_excel('/content/drive/MyDrive/dae_dataset.xlsx',sheet_name = 'Sheet1')
print("Finding the average of feedbacks based on rating")
avg_feedback = df.groupby("Feedback")["Overall_Rating"].mean()
print(avg_feedback)
print("Finding the count of feedbacks based on rating")
feeback_count = df.groupby("Feedback")["Overall_Rating"].count()
print(feeback_count)
print("Finding the maximum of feedbacks based on rating")
max_feedback = df.groupby("Feedback")["Overall_Rating"].max()
print(max_feedback)
print("Finding the minimum of feedbacks based on rating")
min_feedback = df.groupby("Feedback")["Overall_Rating"].min()
print(min_feedback)

Finding the average of feedbacks based on rating
Feedback
Negative    2.0
Neutral     3.0
Positive    4.4
Name: Overall_Rating, dtype: float64
Finding the count of feedbacks based on rating
Feedback
Negative    2
Neutral     1
Positive    5
Name: Overall_Rating, dtype: int64
Finding the maximum of feedbacks based on rating
Feedback
Negative    2
Neutral     3
Positive    5
Name: Overall_Rating, dtype: int64
Finding the minimum of feedbacks based on rating
Feedback
Negative    2
Neutral     3
Positive    4
Name: Overall_Rating, dtype: int64

bar graph

In [17]:
import matplotlib.pyplot as plt
restaurant_rating = df.groupby('Restaurant_Name')['Ambience_Rating'].sum()
plt.figure(figsize=(7,5))
plt.bar(restaurant_rating.index, restaurant_rating.values,color = "steelblue")
plt.xlabel('Restaurant Name')
plt.ylabel('Ambience Rating')
plt.title('Ambience Rating by Restaurant')
plt.tight_layout()
plt.savefig("bar_graph.png",dpi = 120)
plt.close()

pie chart

In [18]:
feedback_count = df['Feedback'].value_counts()
plt.figure(figsize=(6,6))
plt.pie(feedback_count.values,labels = feedback_count.index, autopct = "%1.1f%%", startangle = 90)
plt.title('Feedback Distribution')
plt.tight_layout()
plt.savefig("pie_chart.png",dpi = 120)
plt.close()

box_plot

In [19]:
feedback_values = df["Feedback"].unique()
data_by_feedback = [df[df["Feedback"] == feedback]["Overall_Rating"].dropna() for feedback in feedback_values]
plt.figure(figsize=(8,5))
plt.boxplot(data_by_feedback, tick_labels = feedback_values)
plt.xlabel("Feedback")
plt.ylabel("Overall Rating")
plt.title("Overall Rating Distribution by Feedback")
plt.tight_layout()
plt.savefig("box_plot.png",dpi = 120)
plt.close()

histogram

In [20]:
plt.figure(figsize=(7,5))
plt.hist(df["Food_Rating"].dropna(), bins = 8, color = "mediumseagreen", edgecolor = "black")
plt.xlabel("Food_Rating")
plt.ylabel("Frequency")
plt.title("Distribution of food ratings")
plt.tight_layout()
plt.savefig("histogram.png",dpi = 120)
plt.close()

Line chart

In [21]:
fig, axes = plt.subplots(2,1,figsize=(8,8),sharex = True)
axes[0].plot(df.index,df["Food_Rating"],marker="o",color="royalblue",label="Food Rating")
axes[0].set_title("Food Rating Trend")
axes[0].set_ylabel("Food Rating")
axes[0].legend()
axes[0].grid(True,alpha=0.3)
axes[1].plot(df.index,df["Service_Rating"],marker="s",color="darkorange",label="Service Rating")
axes[1].set_title("Service Rating Trend")
axes[1].set_xlabel("Record Index")
axes[1].set_ylabel("Service Rating")
axes[1].legend()
axes[1].grid(True,alpha=0.3)
plt.tight_layout()
plt.savefig("line_chart_subplots.png",dpi = 120)
plt.close()

scatter plot

In [22]:
plt.figure(figsize=(7,5))
plt.scatter(df["Food_Rating"],df["Overall_Rating"],c = "crimson", edgecolor = "black", alpha = 0.75)
plt.xlabel("Food Rating")
plt.ylabel("Overall Rating")
plt.title("Food Rating vs Overall Rating")
plt.tight_layout()
plt.savefig("scatter_plot.png",dpi = 120)
plt.close()